### ISSUE TITLE
Error: THOR_REST env required

### ISSUE THREAD

**Issue by yeelowsnow** [vechain/mass#15]
Hello,
I followed the implementation steps and am running into an error when starting the backend saying **THOR_REST env required**.
Where do I configure this?

I've added the full stack trace below.

**npm start**

> 

 mass@1.0.0 start /root/mass
 node dist/index.js

/root/mass/dist/thor.js:5
    throw new Error('THOR_REST env required');
    ^

Error: THOR_REST env required
    at Object.<anonymous> (/root/mass/dist/thor.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/mass/dist/db-service/pending.js:26:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mass@1.0.0 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mass@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-25T04_10_01_309Z-debug.log`

**~/.npm/_logs/2021-12-25T04_10_01_309Z-debug.log**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.11
3 info using node@v10.24.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mass@1.0.0~prestart: mass@1.0.0
6 info lifecycle mass@1.0.0~start: mass@1.0.0
7 verbose lifecycle mass@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle mass@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/mass/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle mass@1.0.0~start: CWD: /root/mass
10 silly lifecycle mass@1.0.0~start: Args: [ '-c', 'node dist/index.js' ]
11 silly lifecycle mass@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle mass@1.0.0~start: Failed to exec start script
13 verbose stack Error: mass@1.0.0 start: `node dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mass@1.0.0
15 verbose cwd /root/mass
16 verbose Linux 4.18.0-305.12.1.el8_4.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.24.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error mass@1.0.0 start: `node dist/index.js`
22 error Exit status 1
23 error Failed at the mass@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by libotony** [comment]
[thor](https://github.com/vechain/thor)'s REST API is required to run this project, set the URL to `THOR_REST` in your environment.
