### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'timestamp')

### ISSUE THREAD

**Issue by svgvr8** [vechain/mass#27]
I get the following error, when running.

Listening on port 3000
No tasks for tokens: PLA, SHA, EHrT, DBET, TIC, OCE, SNK, JUR, AQD, YEET, HAI, MDN, VEED, VPU, MVG, WoV, GEMS, VEX, VEUSD, DHN, UNION, VST, PPR, DRAGON, VVET, VSEA, BANANA, GOLD, LGCT
Failed to initialize: TypeError: Cannot read properties of undefined (reading 'timestamp')
    at /Users/mass/dist/db-service/block.js:31:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mass/dist/db-service/block.js:5:58)

**Comment by libotony** [comment]
You need this https://github.com/libotony/chain-scanner, `npm run db-migrate` in chain-scanner will initiate the database, and set mass to connect to the same database

**Comment by svgvr8** [comment]
Thank you. Can you please share the layout for `ormconfig` file used for the backend? I have so far tried mongo, sqlite, better-sqlite and they all seem to have unsupported datatypes, or some other issue.

**Comment by libotony** [comment]
chain-scanner needs mysql https://github.com/libotony/chain-scanner/blob/master/package.json#L8

**Comment by svgvr8** [comment]
Thank you! I'm migrating MySQL DB (v8.0.33) for chain-scanner and I get another TypeError when I run `npm run db-migrate`:

`TypeError: Cannot read properties of undefined (reading 'Value')
at createTable1585191309248.<anonymous> (/1585191309248-create-table.ts:9:22)
    at Generator.next (<anonymous>)
    at fulfilled (/1585191309248-create-table.js:5:58)`

**Comment by libotony** [comment]
@svgvr8 I am currently running on mysql@5.7, and as shown in the code https://github.com/libotony/chain-scanner/blob/b1b0b5f3a07b2809d17c2fce3815b4dacad86d8c/src/migrations/1585191309248-create-table.ts#LL8C48-L8C94, it needs `innodb_file_format=Barracuda`, might be an issue on mysql@8

**Comment by svgvr8** [comment]
thank you! You're a g! Appreciate your help!
